from __future__ import annotations

import mimetypes
import os
import zipfile
from pathlib import Path

from fastapi import HTTPException
from sqlalchemy.orm import Session

from app.models.delivery_pack import DeliveryPack
from app.models.prediction import Prediction
from app.models.user import User
from app.services.delivery_service import _display_title, _slugify, create_comparison_export
from app.services.prediction_service import get_prediction_by_id


def _project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _uploads_root() -> Path:
    uploads_root = (_project_root() / "uploads").resolve()
    uploads_root.mkdir(parents=True, exist_ok=True)
    return uploads_root


def _delivery_packs_root() -> Path:
    packs_root = (_uploads_root() / "delivery_packs").resolve()
    packs_root.mkdir(parents=True, exist_ok=True)
    return packs_root


def _validate_prediction_for_pack(prediction: Prediction) -> None:
    if prediction.status != "completed":
        raise HTTPException(status_code=400, detail="Only completed results can be packaged.")
    if not prediction.original_image_path or not os.path.exists(prediction.original_image_path):
        raise HTTPException(status_code=404, detail="Original image file not found.")
    if not prediction.output_image_path or not os.path.exists(prediction.output_image_path):
        raise HTTPException(status_code=404, detail="Processed image file not found.")


def _pack_filename(prediction: Prediction) -> str:
    title = _display_title(prediction)
    return f"glassclear_delivery_pack_{_slugify(title)}_{prediction.id}.zip"


def _summary_text(prediction: Prediction) -> str:
    title = _display_title(prediction)
    processed_date = (prediction.updated_at or prediction.created_at).isoformat() if (prediction.updated_at or prediction.created_at) else ""
    return "\n".join(
        [
            f"Title: {title}",
            f"Filename: {prediction.original_filename or os.path.basename(prediction.original_image_path or '')}",
            f"Processed Date: {processed_date}",
            f"Status: {prediction.status}",
            "Generated by GlassClear",
        ]
    )


def create_delivery_pack_payload(db: Session, user: User, prediction_id: int) -> dict:
    prediction = get_prediction_by_id(db, prediction_id, user.id)
    _validate_prediction_for_pack(prediction)

    comparison_path = None
    try:
        comparison_path, _ = create_comparison_export(prediction, _display_title(prediction))
        zip_path = _delivery_packs_root() / _pack_filename(prediction)

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.write(prediction.original_image_path, arcname=f"original/{os.path.basename(prediction.original_image_path)}")
            archive.write(prediction.output_image_path, arcname=f"restored/{os.path.basename(prediction.output_image_path)}")
            if comparison_path and os.path.exists(comparison_path):
                archive.write(comparison_path, arcname=f"comparison/{os.path.basename(comparison_path)}")
            archive.writestr("summary.txt", _summary_text(prediction))

        pack = DeliveryPack(prediction_id=prediction.id, user_id=user.id, file_path=str(zip_path))
        db.add(pack)
        db.commit()
        db.refresh(pack)
    finally:
        if comparison_path and os.path.exists(comparison_path):
            try:
                os.remove(comparison_path)
            except OSError:
                pass

    return {
        "pack_id": pack.id,
        "download_url": f"/api/delivery-packs/{pack.id}/download",
        "status": "ready",
    }


def get_delivery_pack_download_payload(db: Session, user: User, pack_id: int) -> tuple[str, str, str]:
    pack = db.query(DeliveryPack).filter(DeliveryPack.id == pack_id, DeliveryPack.user_id == user.id).first()
    if not pack:
        raise HTTPException(status_code=404, detail="Delivery pack not found")
    if not pack.file_path or not os.path.exists(pack.file_path):
        raise HTTPException(status_code=404, detail="Delivery pack file not found")

    filename = os.path.basename(pack.file_path)
    media_type = "application/zip"
    return pack.file_path, filename, media_type
